package protocol

import (
	"encoding/binary"
	"io"
)

// ============================================================================
// API KEYS CONSTANTS
// Description: Standard Kafka ApiKeys supported by our broker.
// ============================================================================
const (
	ApiKeyProduce          int16 = 0
	ApiKeyFetch            int16 = 1
	ApiKeyMetadata         int16 = 3
	ApiKeyOffsetCommit     int16 = 8
	ApiKeyOffsetFetch      int16 = 9
	ApiKeyGroupCoordinator int16 = 10
	ApiKeyJoinGroup        int16 = 11
	ApiKeyHeartbeat        int16 = 12
	ApiKeyLeaveGroup       int16 = 13
	ApiKeySyncGroup        int16 = 14
	ApiKeySaslHandshake    int16 = 17
	ApiKeyApiVersions      int16 = 18
	ApiKeyInitProducerId   int16 = 22
	ApiKeyAddPartitionsToTxn int16 = 24
	ApiKeyEndTxn           int16 = 26
	ApiKeySaslAuthenticate int16 = 36
)

// ============================================================================
// STRUCT: RequestHeader
// Description: Standard Kafka Request Header.
// ============================================================================
type RequestHeader struct {
	ApiKey        int16  // API key identifying the type of request
	ApiVersion    int16  // Version of the API request protocol
	CorrelationId int32  // Unique integer identifier generated by the client to match request and response
	ClientId      string // Identifier for the client application sending the request
}

// ============================================================================
// STRUCT: ResponseHeader
// Description: Standard Kafka Response Header.
// ============================================================================
type ResponseHeader struct {
	CorrelationId int32 // Unique integer identifier matching the CorrelationId from the request
}

// ============================================================================
// FUNCTION: DecodeRequestHeader
// Description: Reads and parses the RequestHeader from an io.Reader stream.
// ============================================================================
func DecodeRequestHeader(r io.Reader) (*RequestHeader, error) {
	apiKey, err := ReadInt16(r)
	if err != nil {
		return nil, err
	}

	apiVersion, err := ReadInt16(r)
	if err != nil {
		return nil, err
	}

	correlationId, err := ReadInt32(r)
	if err != nil {
		return nil, err
	}

	clientId, err := ReadString(r)
	if err != nil {
		return nil, err
	}

	return &RequestHeader{
		ApiKey:        apiKey,
		ApiVersion:    apiVersion,
		CorrelationId: correlationId,
		ClientId:      clientId,
	}, nil
}

// ============================================================================
// FUNCTION: EncodeResponseHeader
// Description: Writes the ResponseHeader to an io.Writer stream.
// ============================================================================
func EncodeResponseHeader(w io.Writer, header *ResponseHeader) error {
	return WriteInt32(w, header.CorrelationId)
}

// ============================================================================
// FUNCTION: EncodeRequestHeader
// Description: Writes the RequestHeader to an io.Writer stream.
// ============================================================================
func EncodeRequestHeader(w io.Writer, header *RequestHeader) error {
	if err := WriteInt16(w, header.ApiKey); err != nil {
		return err
	}
	if err := WriteInt16(w, header.ApiVersion); err != nil {
		return err
	}
	if err := WriteInt32(w, header.CorrelationId); err != nil {
		return err
	}
	return WriteString(w, header.ClientId)
}


// ============================================================================
// PRIMITIVE HELPERS: Readers & Writers
// Description: Utilities for encoding/decoding Kafka protocol primitive types.
// ============================================================================
func ReadInt8(r io.Reader) (int8, error) {
	var buf [1]byte
	if _, err := io.ReadFull(r, buf[:]); err != nil {
		return 0, err
	}
	return int8(buf[0]), nil
}

func ReadInt16(r io.Reader) (int16, error) {
	var buf [2]byte
	if _, err := io.ReadFull(r, buf[:]); err != nil {
		return 0, err
	}
	return int16(binary.BigEndian.Uint16(buf[:])), nil
}

func ReadInt32(r io.Reader) (int32, error) {
	var buf [4]byte
	if _, err := io.ReadFull(r, buf[:]); err != nil {
		return 0, err
	}
	return int32(binary.BigEndian.Uint32(buf[:])), nil
}

func ReadInt64(r io.Reader) (int64, error) {
	var buf [8]byte
	if _, err := io.ReadFull(r, buf[:]); err != nil {
		return 0, err
	}
	return int64(binary.BigEndian.Uint64(buf[:])), nil
}

func ReadString(r io.Reader) (string, error) {
	length, err := ReadInt16(r)
	if err != nil {
		return "", err
	}
	if length <= 0 {
		return "", nil
	}
	buf := make([]byte, length)
	if _, err := io.ReadFull(r, buf); err != nil {
		return "", err
	}
	return string(buf), nil
}

func ReadNullableString(r io.Reader) (*string, error) {
	length, err := ReadInt16(r)
	if err != nil {
		return nil, err
	}
	if length < 0 {
		return nil, nil
	}
	if length == 0 {
		empty := ""
		return &empty, nil
	}
	buf := make([]byte, length)
	if _, err := io.ReadFull(r, buf); err != nil {
		return nil, err
	}
	str := string(buf)
	return &str, nil
}

func ReadBytes(r io.Reader) ([]byte, error) {
	length, err := ReadInt32(r)
	if err != nil {
		return nil, err
	}
	if length <= 0 {
		return nil, nil
	}
	buf := make([]byte, length)
	if _, err := io.ReadFull(r, buf); err != nil {
		return nil, err
	}
	return buf, nil
}

func WriteInt8(w io.Writer, val int8) error {
	_, err := w.Write([]byte{byte(val)})
	return err
}

func WriteInt16(w io.Writer, val int16) error {
	var buf [2]byte
	binary.BigEndian.PutUint16(buf[:], uint16(val))
	_, err := w.Write(buf[:])
	return err
}

func WriteInt32(w io.Writer, val int32) error {
	var buf [4]byte
	binary.BigEndian.PutUint32(buf[:], uint32(val))
	_, err := w.Write(buf[:])
	return err
}

func WriteInt64(w io.Writer, val int64) error {
	var buf [8]byte
	binary.BigEndian.PutUint64(buf[:], uint64(val))
	_, err := w.Write(buf[:])
	return err
}

func WriteString(w io.Writer, val string) error {
	if len(val) == 0 {
		return WriteInt16(w, 0)
	}
	if err := WriteInt16(w, int16(len(val))); err != nil {
		return err
	}
	_, err := w.Write([]byte(val))
	return err
}

func WriteNullableString(w io.Writer, val *string) error {
	if val == nil {
		return WriteInt16(w, -1)
	}
	return WriteString(w, *val)
}

func WriteBytes(w io.Writer, val []byte) error {
	if len(val) == 0 {
		return WriteInt32(w, 0)
	}
	if err := WriteInt32(w, int32(len(val))); err != nil {
		return err
	}
	_, err := w.Write(val)
	return err
}
